version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env